baseline: Hardie's Personal Blog
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
title: Hey Hardie
description: Powered by Cecil.
canonicalurl: true
date:
  format: j F Y
  timezone: Pacific Time
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
optimize:
  enabled: true
baseurl: /
